In [55]:
import numpy
from src import conv
from src.optim.adam import Adam
from src.optim.rmsprop import RMSprop
from src.optim.sgd import SGD
import matplotlib.pyplot as plt

from . import weights

In [9]:
# Creating Convolution layers.
in_array = numpy.array([1, 2, 3, 4, 5])
kernel_1 = numpy.random.randn(3, 1)
stride = 1
padding_1 = 0 

kernel_2 = numpy.random.randn(5, 1)
padding_2 = 1

out = conv.Conv1D(kernel=kernel_1, stride=stride, padding=padding_1)
out_1 = out.forward(in_array=in_array)

out2 = conv.Conv1D(kernel=kernel_2, stride=stride, padding=padding_2)
out_2 = out.forward(in_array=out_1)

print(out_2)

[9.32848656]


In [10]:
# The following three cells are weight initialization techniques.
shape = (3, 3)

weights.uniform(shape)

array([[0.1396748 , 0.98210635, 0.74829089],
       [0.74611196, 0.20609327, 0.09939644],
       [0.40853593, 0.8408422 , 0.57295537]])

In [11]:
weights.kaiming(shape)

array([[ 0.64659937,  0.2323725 , -0.33198808],
       [-0.75841495, -0.48838695,  0.18441022],
       [-0.77990545, -0.43763363,  0.77436081]])

In [12]:
weights.glorot(shape)

array([[ 0.60467984,  0.2860973 , -0.29549778],
       [-0.26148361,  0.47654738, -0.19266389],
       [ 0.06218643, -0.70305784, -0.40863002]])

In [20]:
# Example 3: Adam Optimizer

# For simplicity, we are defining and hardcoding the grad. 
def loss(x): 
    return 2*x**2+4*x+5
def grad(x): 
    return 2*x+4

def converge(w0, w1): 
    return (w0 == w1)

In [47]:
w_0 = 0
b_0 = 0

adam = Adam()
t = 2

is_converged = False

while not is_converged: 
    dw = grad(w_0)
    db = grad(b_0)
    
    w_old = w_0
    w_0, b_0 = adam.update(t, w=w_0, b=b_0, dw=dw, db=db)
    
    if converge(w_old, w_0): 
        print(f"Converged after {t+1} iterations")
        break 
    else: 
        print(f"Iteration: {t+1}, Weight: {w_0}")
        t+=1

Converged after 3 iterations


In [50]:
# Example 4: Using RMSprop 
rms = RMSprop()

while not is_converged:
    dw = grad(w_0)
    db = grad(b_0)
    
    w_old = w_0
    w_0, b_0 = rms.update(t, w=w_0, b=b_0, dw=dw, db=db)
    
    if converge(w_old, w_0): 
        print(f"Converged after {t+1} iterations")
        break 
    else: 
        print(f"Iteration: {t+1}, Weight: {w_0}")
        t+=1

Converged after 3 iterations


In [1]:
# Example 5: Using SGD for Linear Regression
numpy.random.seed(0)

X = numpy.random.rand(100)
y = 2 * X + 1 + numpy.random.randn(100)

sgd = SGD()

m, b, log, mse = sgd.update(X, y)

plt.plot(mse)
plt.xlabel('Epoch')
plt.ylabel('MSE')
plt.show()

NameError: name 'numpy' is not defined